### ISSUE TITLE
Clarification on OSX Serial Port

### ISSUE THREAD

**Issue by danshev** [redbear/Duo#11]
Brand new to this and not clear on [this step](https://github.com/redbear/Duo/blob/master/docs/getting_started.md#for-osx-or-linux) in the Getting Started document:

    $ screen /dev/tty.usbmodemXXXXX

    where XXXXX is your Duo device serial port.

Where / how does one find the XXXXX?

**Comment by kennethlimcp** [comment]
An easier solution is to use things like CoolTerm.. Or `ls /dev/tty.usbmodem*`

**Comment by danshev** [comment]
Very nice, thank you -- I highly recommend that make its way into the document.

**Comment by Cheong2K** [comment]
Added to the doc., thanks.
