### ISSUE TITLE
Windows WDF_VIOLATION error

### ISSUE THREAD

**Issue by LeonardoGuimaraes** [redbear/Duo#12]
Hi,
Yesterday I was testing my RedBear Duo with the Duo_RGB sketch and it was working perfectly. After that, I tried to to update the firmware via DFU-Util but it did not work. I also confurated the Wifi via Putty (this part i think worked, the GREEN LED was flashing after the process).

But today, I can not upload another sketch, because appear the error "Port Busy". If I press any button (SETUP or RESET) or unplug the board, my computer runs into the error WDF_VIOLATION (appear the famous blue screen and restart the computer).

Any ideia about what is happening?

**Comment by Cheong2K** [comment]
Hi, please make use of the RedBear's discussion forum for technical support so that other users may help.
