### ISSUE TITLE
HomeKit sample code

### ISSUE THREAD

**Issue by ericcastro** [redbear/Duo#15]
Hi, can you please upload the sample code for HomeKit stuff?

Like the example you show in this video:
https://www.youtube.com/watch?v=-m54v82nr00

**Comment by Cheong2K** [comment]
Sorry, we cannot release MFi code in public. Please see this to get the SDK from Broadcom and compile the Lightbulb example, you can discuss inside the Broadcom WiFi MFi forum.

**Comment by Cheong2K** [comment]
https://github.com/redbear/WICED-SDK

**Comment by ericcastro** [comment]
If I want to make a HomeKit app **for personal use,** do I still need an MFi license ?

**Comment by Cheong2K** [comment]
No, you will not get the MFi SDK from Broadcom if you do not have the license number.
