### ISSUE TITLE
Can't find device with dfu-util

### ISSUE THREAD

**Issue by toolmacher** [redbear/Duo#16]
Hi,
i followed the instructions of windows driver installation and dfu-util. But when I typed in ``dfu-util -l" the following message prompts: Cannot open DFU device 2b04:d058. 
The device manager  shows up "Duo DFU Mode", but with a exclamation mark.
I tried serval times to reinstall the usb driver.
Any ideas, what's I'm doing wrong?
I use Windows 10 home,

**Comment by Cheong2K** [comment]
Hi, kindly please post your question in their support forum for help: http://discuss.redbear.cc/
