### ISSUE TITLE
Provide option on Arduino to upload through RBLink

### ISSUE THREAD

**Issue by rei-vilo** [redbear/Duo#2]
Provide option on Arduino to compile and upload through RBLink, as the RBDuo appears as a mass storage device to drag-and-drop the executable into, _à la_ mbed.

**Comment by Cheong2K** [comment]
We are working on using OpenOCD to burn system firmwares and user part using the RBLink from Arduino IDE.

**Comment by Cheong2K** [comment]
@rei-vilo, would you mind to help to test uploading sketches using the RBLink (with Board Package 0.2.7)?
Ref.:
https://github.com/redbear/STM32-Arduino

**Comment by rei-vilo** [comment]
Sure, where can I find the procedure? It doesn't seem to have been published yet on the linked page.

**Comment by rei-vilo** [comment]
Ok, `RedBear Duo (RBLink USB Port)` now appears on the boards after updating to release 0.2.7.

Upload works fine. Console serial is `Serial1`.

When connecting the RBLink, a mass storage device appears names `RBLink` is mounted. Any plans to implement a copy-paste-program like in mbed?
