### ISSUE TITLE
Tutorials Needed

### ISSUE THREAD

**Issue by beyersito** [redbear/Duo#20]
Where can I find a goodf tutorial, especially oriented to the ble part, I have experience with arduino and rpi, but I cant seem to find any on Duo. Thanks!

**Comment by XuGuohui** [comment]
Please take a look at this reference manual:

https://github.com/redbear/Duo/blob/master/docs/programming_reference_manual.md#bluetooth-low-energy-ble

If you want to learn about the BLE specification, you'd better go to Bluetooth SIG:

https://developer.bluetooth.org/TechnologyOverview/Pages/core-specification.aspx

Cheers!
