### ISSUE TITLE
Add link in Readme.md to Duo examples

### ISSUE THREAD

**Issue by peterfox** [redbear/Duo#9]
Can you please add a link in the readme file to [the examples](https://github.com/redbear/STM32-Arduino/tree/master/arduino/libraries/RedBear_Duo/examples) I had trouble finding any of these and I'm sure they would be useful for others to know when getting started.

**Comment by XuGuohui** [comment]
Documentation for Duo is updated: https://github.com/redbear/Duo#documentation
Resources: https://github.com/redbear/Duo#resources

Cheers!

**Comment by peterfox** [comment]
:thumbsup: thank you!
